global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "express-app"
    static_configs:
      - targets: ["app:5000"]
  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb:27017"]
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
